image:
  file: Dockerfile

tasks:
  - init: |
      pip install -r requirements.txt
      python -m pip install --upgrade pip
    command: |
      python train.py --data data/diamond.yaml --cfg cfg/training/yolov7.yaml --weights yolov7.pt

ports:
  - port: 8888
    onOpen: open-preview

vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
